### ISSUE TITLE
Resolve errors with PropertiesPanelModule

### ISSUE THREAD

**Issue by jordanurbs** [xanpj/postit-js-extensions#4]
Hi, I've installed DragDropImagesModule and SelectionOrganizerModule extensions fine (manually), but keep getting these errors with PropertiesPanelModule

`ERROR in ../lib/features/entry-factory/EntryFactory.js 1:0-4:46
Module not found: Error: Can't resolve 'postit-js-core/lib/util/ModelUtil.js' in '/postit-js/lib/features/entry-factory'
 @ ../lib/features/entry-factory/index.js 1:0-42 5:26-38
 @ ../lib/features/properties-panel-v2/index.js 2:0-50 6:4-22
 @ ../lib/Modeler.js 35:0-61 119:2-17
 @ ./app/app.js 4:0-55 10:18-31

ERROR in ../lib/features/properties-panel-v2/PropertiesPanel.js 13:0-15:19
Module not found: Error: Can't resolve 'immutable' in '/postit-js/lib/features/properties-panel-v2'
 @ ../lib/features/properties-panel-v2/index.js 1:0-48 9:29-44
 @ ../lib/Modeler.js 35:0-61 119:2-17
 @ ./app/app.js 4:0-55 10:18-31

ERROR in ../lib/features/properties-panel-v2/PropertiesPanel.js 46:0-53:73
Module not found: Error: Can't resolve 'postit-js-extensions/lib/features/entry-factory/EntryFactory.js' in '/postit-js/lib/features/properties-panel-v2'
 @ ../lib/features/properties-panel-v2/index.js 1:0-48 9:29-44
 @ ../lib/Modeler.js 35:0-61 119:2-17
 @ ./app/app.js 4:0-55 10:18-31

ERROR in ../lib/features/properties-panel-v2/PropertiesPanelUtil.js 1:0-3:46
Module not found: Error: Can't resolve 'postit-js-core/lib/util/ModelUtil.js' in '/postit-js/lib/features/properties-panel-v2'
 @ ../lib/features/properties-panel-v2/PropertiesPanel.js 21:0-31:34 132:38-72 133:29-54 134:27-50 135:29-54 137:26-48 138:23-41 684:14-37 686:14-37 689:12-35
 @ ../lib/features/properties-panel-v2/index.js 1:0-48 9:29-44
 @ ../lib/Modeler.js 35:0-61 119:2-17
 @ ./app/app.js 4:0-55 10:18-31

ERROR in ../lib/features/properties-panel-v2/PropertiesPanelUtil.js 9:0-15:73
Module not found: Error: Can't resolve 'postit-js-extensions/lib/features/entry-factory/EntryFactory.js' in '/postit-js/lib/features/properties-panel-v2'
 @ ../lib/features/properties-panel-v2/PropertiesPanel.js 21:0-31:34 132:38-72 133:29-54 134:27-50 135:29-54 137:26-48 138:23-41 684:14-37 686:14-37 689:12-35
 @ ../lib/features/properties-panel-v2/index.js 1:0-48 9:29-44
 @ ../lib/Modeler.js 35:0-61 119:2-17
 @ ./app/app.js 4:0-55 10:18-31`

**Comment by xanpj** [comment]
Hi, you are absolutely right. For some reason I never pushed those helper functions to the main `postit-js` project.

I now included them in the extensions themselves.

Just fixed it in the latest commit. [2d845605d844cf36038cd42dc096859d3b0b2c2d](https://github.com/xanpj/postit-js-extensions/commit/2d845605d844cf36038cd42dc096859d3b0b2c2d)

**Comment by jordanurbs** [comment]
Thanks!
